//go:build ignore

// Package main generates the helper bounds from the frozen successor checkpoint.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"io"
	"os"
	"strconv"
)

const (
	limitsInputPath  = "../../tests/fixtures/github_ci_successor_checkpoint/limits.json"
	limitsOutputPath = "limits_gen.go"
)

type limitSpec struct {
	jsonKey string
	goName  string
}

var requiredLimits = []limitSpec{
	{jsonKey: "aggregate_request_cap_bytes", goName: "aggregateRequestCapBytes"},
	{jsonKey: "helper_source_cap_bytes", goName: "helperSourceCapBytes"},
	{jsonKey: "max_sources_per_batch", goName: "maxSourcesPerBatch"},
	{jsonKey: "json_max_depth", goName: "jsonMaxDepth"},
	{jsonKey: "statement_cap", goName: "statementCap"},
	{jsonKey: "visitor_node_cap", goName: "visitorNodeCap"},
	{jsonKey: "visitor_depth_cap", goName: "visitorDepthCap"},
	{jsonKey: "event_cap", goName: "eventCap"},
	{jsonKey: "max_argv_words_per_site", goName: "maxArgvWordsPerSite"},
	{jsonKey: "max_assignments_per_site", goName: "maxAssignmentsPerSite"},
}

func main() {
	if err := generateLimits(); err != nil {
		fmt.Fprintf(os.Stderr, "generate limits: %v\n", err)
		os.Exit(1)
	}
}

func generateLimits() error {
	data, err := os.ReadFile(limitsInputPath)
	if err != nil {
		return fmt.Errorf("read %s: %w", limitsInputPath, err)
	}
	document, err := decodeUniqueJSONObject(data)
	if err != nil {
		return fmt.Errorf("decode %s: %w", limitsInputPath, err)
	}

	values := make([]int, len(requiredLimits))
	for index, spec := range requiredLimits {
		value, err := requiredInt(document, spec.jsonKey)
		if err != nil {
			return err
		}
		values[index] = value
	}

	var output bytes.Buffer
	output.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	output.WriteString("// Package main contains helper bounds generated from the frozen checkpoint.\n")
	output.WriteString("package main\n\n")
	output.WriteString("const (\n")
	for index, spec := range requiredLimits {
		fmt.Fprintf(&output, "\t%s int = %d\n", spec.goName, values[index])
	}
	output.WriteString(")\n")

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return fmt.Errorf("format generated limits: %w", err)
	}
	if err := os.WriteFile(limitsOutputPath, formatted, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", limitsOutputPath, err)
	}
	return nil
}

func decodeUniqueJSONObject(data []byte) (map[string]json.RawMessage, error) {
	decoder := json.NewDecoder(bytes.NewReader(data))
	opening, err := decoder.Token()
	if err != nil {
		return nil, err
	}
	if opening != json.Delim('{') {
		return nil, errors.New("limits checkpoint must be a JSON object")
	}

	document := make(map[string]json.RawMessage)
	for decoder.More() {
		keyToken, err := decoder.Token()
		if err != nil {
			return nil, err
		}
		key, ok := keyToken.(string)
		if !ok {
			return nil, errors.New("limits checkpoint contains a non-string object key")
		}
		if _, exists := document[key]; exists {
			return nil, fmt.Errorf("duplicate JSON field %q", key)
		}
		var value json.RawMessage
		if err := decoder.Decode(&value); err != nil {
			return nil, err
		}
		document[key] = value
	}
	closing, err := decoder.Token()
	if err != nil {
		return nil, err
	}
	if closing != json.Delim('}') {
		return nil, errors.New("limits checkpoint has an invalid object terminator")
	}
	var trailing any
	if err := decoder.Decode(&trailing); err != io.EOF {
		return nil, errors.New("limits checkpoint contains trailing JSON data")
	}
	return document, nil
}

func requiredInt(document map[string]json.RawMessage, key string) (int, error) {
	raw, exists := document[key]
	if !exists {
		return 0, fmt.Errorf("limits checkpoint is missing %q", key)
	}
	if len(raw) == 0 {
		return 0, fmt.Errorf("limit %q is empty", key)
	}
	start := 0
	if raw[0] == '-' {
		start = 1
	}
	if start == len(raw) {
		return 0, fmt.Errorf("limit %q must be an integer", key)
	}
	for _, digit := range raw[start:] {
		if digit < '0' || digit > '9' {
			return 0, fmt.Errorf("limit %q must be an integer", key)
		}
	}
	value, err := strconv.ParseInt(string(raw), 10, 64)
	if err != nil {
		return 0, fmt.Errorf("limit %q is outside the supported integer range: %w", key, err)
	}
	maxInt := int64(^uint(0) >> 1)
	minInt := -maxInt - 1
	if value < minInt || value > maxInt {
		return 0, fmt.Errorf("limit %q is outside the platform int range", key)
	}
	if value <= 0 {
		return 0, fmt.Errorf("limit %q must be positive", key)
	}
	if key == "aggregate_request_cap_bytes" && value == maxInt {
		return 0, fmt.Errorf("limit %q leaves no integer headroom for bounded reading", key)
	}
	return int(value), nil
}
