// Code generated by go generate; DO NOT EDIT.

// Package main contains helper bounds generated from the frozen checkpoint.
package main

const (
	aggregateRequestCapBytes int = 8388608
	helperSourceCapBytes     int = 4194304
	maxSourcesPerBatch       int = 4096
	jsonMaxDepth             int = 64
	statementCap             int = 65536
	visitorNodeCap           int = 100000
	visitorDepthCap          int = 200
	eventCap                 int = 10000
	maxArgvWordsPerSite      int = 4096
	maxAssignmentsPerSite    int = 256
)
